version: '3.8'

services:
  bichon:
    image: rustmailer/bichon:latest
    container_name: bichon
    restart: unless-stopped
    ports:
      - "15630:15630"
    environment:
      - BICHON_ROOT_DIR=/data
      - BICHON_ENABLE_ACCESS_TOKEN=true
      - BICHON_LOG_LEVEL=${BICHON_LOG_LEVEL:-info}
    env_file:
      - ./.env
    volumes:
      - ./data:/data
    networks:
      - caddy_network

networks:
  caddy_network:
    external: true
