services:
  speedtest:
    image: ghcr.io/mrcodeeu/homelab-speedtest:latest
    container_name: ${COMPOSE_PROJECT_NAME:-speedtest}
    restart: unless-stopped
    ports:
      - "8089:8080"  # Production port
    volumes:
      - speedtest-data:/app/data
    networks:
      - speedtest

networks:
  speedtest:
    driver: bridge

volumes:
  speedtest-data:
    driver: local
