services:
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    volumes:
      - ./configuration.yml:/config/configuration.yml
      - ./users_database.yml:/config/users_database.yml
      - ./db.sqlite3:/config/db.sqlite3
      - ./notification.txt:/config/notification.txt
    ports:
      - "9091:9091"
    environment:
      - TZ=Europe/Vienna
    restart: unless-stopped
    healthcheck:
      disable: true
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: authelia_redis
    volumes:
      - redis_data:/data
    restart: unless-stopped
    expose:
      - 6379

volumes:
  redis_data:
