services:
  sudoku:
    image: ghcr.io/mrcodeeu/sudoku-gen:latest
    container_name: sudoku
    restart: unless-stopped
    ports:
      - "3602:3000"
    environment:
      - SUDOKU_API_USER=${SUDOKU_API_USER}
      - SUDOKU_API_PASSWORD=${SUDOKU_API_PASSWORD}
    volumes:
      - sudoku-data:/data

volumes:
  sudoku-data:
    driver: local
