package backupdashboard

import (
	"context"
	"encoding/json"
	"fmt"
	"math"
	"os"
	"sort"
	"strings"
	"time"
)

func round1(v float64) float64 {
	return math.Round(v*10) / 10
}

// CatalogEntry is one row of backup_catalog.json, generated by Puppet's
// roles::backup_dashboard.
type CatalogEntry struct {
	Name         string   `json:"name"`
	Type         string   `json:"type"`
	Host         string   `json:"host"`
	Source       any      `json:"source"` // string or []string
	Dest         string   `json:"dest,omitempty"`
	Destinations []string `json:"destinations"`
}

// SourceDisplay renders Source (string or []string in the JSON) as the
// comma-joined text the page shows.
func (e CatalogEntry) SourceDisplay() string {
	switch v := e.Source.(type) {
	case string:
		return v
	case []any:
		parts := make([]string, 0, len(v))
		for _, s := range v {
			if str, ok := s.(string); ok {
				parts = append(parts, str)
			}
		}
		return strings.Join(parts, ", ")
	default:
		return ""
	}
}

type Catalog struct {
	GeneratedAt string         `json:"generated_at"`
	Entries     []CatalogEntry `json:"entries"`
}

func loadCatalog(path string) (*Catalog, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var cat Catalog
	if err := json.Unmarshal(raw, &cat); err != nil {
		return nil, err
	}
	return &cat, nil
}

// HostStatus is one host's reduced backup state - Phase 1 limitation
// (surfaced on the page, not hidden): this is the host's last backup run
// as a whole, not per-entry. See EntryBadge.
type HostStatus struct {
	State          string   `json:"state"`
	Reason         string   `json:"reason,omitempty"`
	FailedServices []string `json:"failed_services"`
	AgeSeconds     *float64 `json:"age_seconds"`
}

func hostStatus(payload *FactsPayload, fetchErrMsg string) HostStatus {
	if fetchErrMsg != "" {
		return HostStatus{State: "unknown", Reason: fetchErrMsg, FailedServices: []string{}}
	}
	backup := payload.Sections.Backup.Data
	if !backup.Available {
		reason := backup.Reason
		if reason == "" {
			reason = "no data"
		}
		return HostStatus{State: "unknown", Reason: reason, FailedServices: []string{}}
	}
	state := "degraded"
	if backup.Completed && backup.CriticalFailures == 0 {
		state = "ok"
	}
	failed := backup.FailedServices
	if failed == nil {
		failed = []string{}
	}
	return HostStatus{State: state, FailedServices: failed, AgeSeconds: backup.AgeSeconds}
}

// DestUsage is one remote destination's capacity, as shown in the
// capacity cards.
type DestUsage struct {
	UsedPercent float64 `json:"used_percent"`
	FreeGiB     float64 `json:"free_gib"`
}

// targetUsage extracts {target_name: usage} from one host's facts
// payload. Only kind == "remote" (pcloud/ugreen/wd-cloud) -
// collect_backup_targets also reports kind == "local" entries (borg/appdata
// staging paths on nas), which are real disk usage but not "destinations"
// in the sense the capacity cards mean. Confirmed live in the Python
// original: without this filter, nas's local staging paths showed up as
// destination cards next to pcloud.
func targetUsage(payload *FactsPayload, fetchErrMsg string) map[string]DestUsage {
	out := map[string]DestUsage{}
	if fetchErrMsg != "" || payload == nil {
		return out
	}
	for _, t := range payload.Sections.BackupTargets.Data.Targets {
		if t.Kind != "remote" {
			continue
		}
		if !t.QuotaSupported || t.UsedPercent == nil {
			continue
		}
		free := 0.0
		if t.FreeBytes != nil {
			free = *t.FreeBytes
		}
		out[t.Name] = DestUsage{
			UsedPercent: round1(*t.UsedPercent),
			FreeGiB:     round1(free / (1024 * 1024 * 1024)),
		}
	}
	return out
}

// EntryBadge decides whether this specific catalog entry is named in its
// host's failure list.
//
// The three backup scripts format a failure differently (see
// ansible/roles/unraid-backup/templates/backup.sh.j2 and ansible/roles/
// backup/templates/backup.sh.j2): the pcloud leg uses the raw dest string
// ("pcloud:Fotos"), the ugreen/wd_cloud legs append "(leg)" to the entry
// name, and the rocky `backup` role's service failures are the bare
// service name. A substring check on the name covers the two name-based
// formats; an exact check against Dest covers the pcloud one.
func EntryBadge(entry CatalogEntry, statuses map[string]HostStatus) string {
	hostState := statuses[entry.Host]
	for _, item := range hostState.FailedServices {
		if item == entry.Dest || strings.Contains(item, entry.Name) {
			return "failed"
		}
	}
	if hostState.State != "" {
		return hostState.State
	}
	return "unknown"
}

// EntryWithBadge pairs a catalog entry with its computed state, ready to render.
type EntryWithBadge struct {
	CatalogEntry
	Badge string `json:"badge"`
}

type Snapshot struct {
	GeneratedAt        string                        `json:"generated_at"`
	CatalogGeneratedAt string                        `json:"catalog_generated_at"`
	HostOrder          []string                      `json:"-"`
	Hosts              map[string]HostStatus         `json:"hosts"`
	DestinationOrder   []string                      `json:"-"`
	Destinations       map[string]DestUsage          `json:"destinations"`
	SourceDisk         map[string]map[string]float64 `json:"source_disk"`
	Entries            []EntryWithBadge              `json:"entries"`
	Errors             map[string]string             `json:"errors"`
}

func BuildSnapshot(ctx context.Context, cfg Config) (*Snapshot, error) {
	catalog, err := loadCatalog(cfg.CatalogPath)
	if err != nil {
		return nil, fmt.Errorf("load catalog: %w", err)
	}

	payloads, errs := FetchAll(ctx, cfg)

	hostOrder := make([]string, 0, len(cfg.SSHHosts))
	statuses := map[string]HostStatus{}
	for _, h := range cfg.SSHHosts {
		hostOrder = append(hostOrder, h.Name)
		statuses[h.Name] = hostStatus(payloads[h.Name], errs[h.Name])
	}

	// Destination usage is only meaningful from whichever host actually
	// has rclone configured against it - any host that returns targets
	// works, the remotes are the same wherever they are configured.
	destinations := map[string]DestUsage{}
	for _, h := range cfg.SSHHosts {
		for name, usage := range targetUsage(payloads[h.Name], errs[h.Name]) {
			destinations[name] = usage
		}
	}
	destOrder := make([]string, 0, len(destinations))
	for name := range destinations {
		destOrder = append(destOrder, name)
	}
	sort.Strings(destOrder)

	sourceDisk := SourceDiskUsage(ctx, cfg.VictoriaURL)

	entries := make([]EntryWithBadge, 0, len(catalog.Entries))
	for _, entry := range catalog.Entries {
		entries = append(entries, EntryWithBadge{
			CatalogEntry: entry,
			Badge:        EntryBadge(entry, statuses),
		})
	}

	return &Snapshot{
		GeneratedAt:        time.Now().UTC().Format(time.RFC3339),
		CatalogGeneratedAt: catalog.GeneratedAt,
		HostOrder:          hostOrder,
		Hosts:              statuses,
		DestinationOrder:   destOrder,
		Destinations:       destinations,
		SourceDisk:         sourceDisk,
		Entries:            entries,
		Errors:             errs,
	}, nil
}
