package backupdashboard

import (
	"context"
	"encoding/json"
	"fmt"
	"math"
	"os"
	"sort"
	"strings"
	"time"
)

func round1(v float64) float64 {
	return math.Round(v*10) / 10
}

// CatalogEntry is one row of backup_catalog.json, generated by Puppet's
// roles::backup_dashboard.
type CatalogEntry struct {
	Name         string   `json:"name"`
	Type         string   `json:"type"`
	Host         string   `json:"host"`
	Source       any      `json:"source"` // string or []string
	Dest         string   `json:"dest,omitempty"`
	Destinations []string `json:"destinations"`
	// Schedule is a plain HH:MM:SS time-of-day, sourced from
	// roles::backup_dashboard's $host_schedules - not a full systemd
	// OnCalendar parser, since every real schedule in this repo today is a
	// simple fixed daily time. A future non-daily schedule would silently
	// render something wrong here.
	Schedule string `json:"schedule,omitempty"`
}

// SourceDisplay renders Source (string or []string in the JSON) as the
// comma-joined text the page shows.
func (e CatalogEntry) SourceDisplay() string {
	switch v := e.Source.(type) {
	case string:
		return v
	case []any:
		parts := make([]string, 0, len(v))
		for _, s := range v {
			if str, ok := s.(string); ok {
				parts = append(parts, str)
			}
		}
		return strings.Join(parts, ", ")
	default:
		return ""
	}
}

type Catalog struct {
	GeneratedAt string         `json:"generated_at"`
	Entries     []CatalogEntry `json:"entries"`
}

func loadCatalog(path string) (*Catalog, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var cat Catalog
	if err := json.Unmarshal(raw, &cat); err != nil {
		return nil, err
	}
	return &cat, nil
}

// HostStatus is one host's reduced backup state - Phase 1 limitation
// (surfaced on the page, not hidden): this is the host's last backup run
// as a whole, not per-entry. See EntryBadge.
type HostStatus struct {
	State             string               `json:"state"`
	Reason            string               `json:"reason,omitempty"`
	FailedServices    []string             `json:"failed_services"`
	AgeSeconds        *float64             `json:"age_seconds"`
	Stats             map[string]EntryStat `json:"-"`
	VerificationState string               `json:"verification_state,omitempty"`
	VerificationAt    string               `json:"verification_at,omitempty"`
	VerificationMode  string               `json:"verification_mode,omitempty"`
	RestoreState      string               `json:"restore_state,omitempty"`
	RestoreAt         string               `json:"restore_at,omitempty"`
}

func hostStatus(payload *FactsPayload, fetchErrMsg string) HostStatus {
	if fetchErrMsg != "" {
		return HostStatus{State: "unknown", Reason: fetchErrMsg, FailedServices: []string{}}
	}
	backup := payload.Sections.Backup.Data
	if !backup.Available {
		reason := backup.Reason
		if reason == "" {
			reason = "no data"
		}
		return HostStatus{State: "unknown", Reason: reason, FailedServices: []string{}}
	}
	state := "degraded"
	if backup.Completed && backup.CriticalFailures == 0 {
		state = "ok"
	}
	failed := backup.FailedServices
	if failed == nil {
		failed = []string{}
	}
	verification := payload.Sections.BackupVerification.Data
	verificationState := "unknown"
	if verification.Available {
		verificationState = verification.State
	}
	restore := verification.Checks["restore"]
	return HostStatus{State: state, FailedServices: failed, AgeSeconds: backup.AgeSeconds, Stats: backup.Stats,
		VerificationState: verificationState, VerificationAt: verification.UpdatedAt, VerificationMode: verification.LastMode,
		RestoreState: restore.State, RestoreAt: restore.UpdatedAt}
}

// DestUsage is one remote destination's capacity, as shown in the
// capacity cards.
type DestUsage struct {
	UsedPercent float64 `json:"used_percent"`
	FreeGiB     float64 `json:"free_gib"`
}

// HistoryStatus is the Btrfs snapshot-history target, which is deliberately
// separate from a backup source host: it has no backup run of its own.
type HistoryStatus struct {
	Name           string   `json:"name"`
	State          string   `json:"state"`
	Reason         string   `json:"reason,omitempty"`
	SnapshotCount  int      `json:"snapshot_count"`
	LatestSnapshot *string  `json:"latest_snapshot,omitempty"`
	FreePercent    *float64 `json:"free_percent,omitempty"`
	FloorPercent   int      `json:"floor_percent"`
}

func historyStatus(name string, payload *FactsPayload, fetchErrMsg string) (HistoryStatus, bool) {
	if fetchErrMsg != "" || payload == nil {
		return HistoryStatus{}, false
	}
	history := payload.Sections.BackupHistory.Data
	if !history.Available && history.State == "" && history.Reason == "" {
		return HistoryStatus{}, false
	}
	return HistoryStatus{Name: name, State: history.State, Reason: history.Reason,
		SnapshotCount: history.SnapshotCount, LatestSnapshot: history.LatestSnapshot,
		FreePercent: history.FreePercent, FloorPercent: history.FloorPercent}, true
}

// targetUsage extracts {target_name: usage} from one host's facts
// payload. Only kind == "remote" (pcloud/ugreen/wd-cloud) -
// collect_backup_targets also reports kind == "local" entries (borg/appdata
// staging paths on nas), which are real disk usage but not "destinations"
// in the sense the capacity cards mean. Confirmed live in the Python
// original: without this filter, nas's local staging paths showed up as
// destination cards next to pcloud.
func targetUsage(payload *FactsPayload, fetchErrMsg string) map[string]DestUsage {
	out := map[string]DestUsage{}
	if fetchErrMsg != "" || payload == nil {
		return out
	}
	for _, t := range payload.Sections.BackupTargets.Data.Targets {
		if t.Kind != "remote" {
			continue
		}
		if !t.QuotaSupported || t.UsedPercent == nil {
			continue
		}
		free := 0.0
		if t.FreeBytes != nil {
			free = *t.FreeBytes
		}
		out[t.Name] = DestUsage{
			UsedPercent: round1(*t.UsedPercent),
			FreeGiB:     round1(free / (1024 * 1024 * 1024)),
		}
	}
	return out
}

// EntryBadge decides whether this specific catalog entry is named in its
// host's failure list.
//
// The three backup scripts format a failure differently (see
// ansible/roles/unraid-backup/templates/backup.sh.j2 and ansible/roles/
// backup/templates/backup.sh.j2): the pcloud leg uses the raw dest string
// ("pcloud:Fotos"), the ugreen/wd_cloud legs append "(leg)" to the entry
// name, and the rocky `backup` role's service failures are the bare
// service name. A substring check on the name covers the two name-based
// formats; an exact check against Dest covers the pcloud one.
func EntryBadge(entry CatalogEntry, statuses map[string]HostStatus) string {
	hostState := statuses[entry.Host]
	for _, item := range hostState.FailedServices {
		if item == entry.Dest || strings.Contains(item, entry.Name) {
			return "failed"
		}
	}
	if hostState.State != "" {
		return hostState.State
	}
	return "unknown"
}

// EntryStatFor looks up an entry's backed-up size, keyed the same way as
// EntryBadge's own name matching: the catalog entry's Name matches the key
// backup.sh.epp/backup-content.sh use in their BACKUP_STATS log lines
// exactly (rocky's service name, nas's path name) - no substring matching
// needed here since these are exact identifiers, not free-text failure
// strings.
func EntryStatFor(entry CatalogEntry, statuses map[string]HostStatus) (EntryStat, bool) {
	stat, ok := statuses[entry.Host].Stats[entry.Name]
	return stat, ok
}

// EntryWithBadge pairs a catalog entry with its computed state, ready to render.
type EntryWithBadge struct {
	CatalogEntry
	Badge     string `json:"badge"`
	SizeBytes int64  `json:"size_bytes,omitempty"`
	FileCount int64  `json:"file_count,omitempty"`
	HasStats  bool   `json:"has_stats,omitempty"`
}

type Snapshot struct {
	GeneratedAt        string                        `json:"generated_at"`
	CatalogGeneratedAt string                        `json:"catalog_generated_at"`
	HostOrder          []string                      `json:"-"`
	Hosts              map[string]HostStatus         `json:"hosts"`
	DestinationOrder   []string                      `json:"-"`
	Destinations       map[string]DestUsage          `json:"destinations"`
	History            []HistoryStatus               `json:"history,omitempty"`
	SourceDisk         map[string]map[string]float64 `json:"source_disk"`
	Entries            []EntryWithBadge              `json:"entries"`
	Errors             map[string]string             `json:"errors"`
}

func BuildSnapshot(ctx context.Context, cfg Config) (*Snapshot, error) {
	catalog, err := loadCatalog(cfg.CatalogPath)
	if err != nil {
		return nil, fmt.Errorf("load catalog: %w", err)
	}

	payloads, errs := FetchAll(ctx, cfg)

	sourceHosts := map[string]bool{}
	for _, entry := range catalog.Entries {
		sourceHosts[entry.Host] = true
	}
	hostOrder := make([]string, 0, len(sourceHosts))
	statuses := map[string]HostStatus{}
	history := []HistoryStatus{}
	for _, h := range cfg.SSHHosts {
		if sourceHosts[h.Name] {
			hostOrder = append(hostOrder, h.Name)
			statuses[h.Name] = hostStatus(payloads[h.Name], errs[h.Name])
		}
		if status, ok := historyStatus(h.Name, payloads[h.Name], errs[h.Name]); ok {
			history = append(history, status)
		}
	}

	// Destination usage is only meaningful from whichever host actually
	// has rclone configured against it - any host that returns targets
	// works, the remotes are the same wherever they are configured.
	destinations := map[string]DestUsage{}
	for _, h := range cfg.SSHHosts {
		for name, usage := range targetUsage(payloads[h.Name], errs[h.Name]) {
			destinations[name] = usage
		}
	}
	destOrder := make([]string, 0, len(destinations))
	for name := range destinations {
		destOrder = append(destOrder, name)
	}
	sort.Strings(destOrder)

	sourceDisk := SourceDiskUsage(ctx, cfg.VictoriaURL)

	entries := make([]EntryWithBadge, 0, len(catalog.Entries))
	for _, entry := range catalog.Entries {
		stat, hasStats := EntryStatFor(entry, statuses)
		entries = append(entries, EntryWithBadge{
			CatalogEntry: entry,
			Badge:        EntryBadge(entry, statuses),
			SizeBytes:    stat.Bytes,
			FileCount:    stat.Files,
			HasStats:     hasStats,
		})
	}

	return &Snapshot{
		GeneratedAt:        time.Now().UTC().Format(time.RFC3339),
		CatalogGeneratedAt: catalog.GeneratedAt,
		HostOrder:          hostOrder,
		Hosts:              statuses,
		DestinationOrder:   destOrder,
		Destinations:       destinations,
		History:            history,
		SourceDisk:         sourceDisk,
		Entries:            entries,
		Errors:             errs,
	}, nil
}
