services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: ${COMPOSE_PROJECT_NAME:-pocketbase}
    restart: unless-stopped
    ports:
      - "8091:8090"
    volumes:
      - pocketbase-data:/pb_data
    networks:
      - pocketbase

networks:
  pocketbase:
    driver: bridge

volumes:
  pocketbase-data:
    driver: local
