services:
  sudoku:
    image: ghcr.io/mrcodeeu/sudoku-gen:latest
    container_name: sudoku
    restart: unless-stopped
    ports:
      - "3602:3000"
    volumes:
      - sudoku-data:/data

volumes:
  sudoku-data:
    driver: local
