// DNS as code for mljr.eu, hosted at deSEC. Apply with:
//   DESEC_TOKEN=... dnscontrol preview|push
// Only mljr.eu is managed here (see README.md).

var REG_NONE = NewRegistrar("none");
var DSP_DESEC = NewDnsProvider("desec");

var MAIL = "mail.mljr.eu.";
var VPS_V4 = "157.173.97.107";
var VPS_V6 = "2a02:c207:2294:5702::1";

D("mljr.eu", REG_NONE, DnsProvider(DSP_DESEC),
  DefaultTTL(3600),

  // Not managed here: the DKIM key is generated by Mailcow and rotated there
  // (Admin UI -> DKIM), so it stays out of git. Apex NS needs no IGNORE: the
  // deSEC provider already handles it (IGNORE on it trips the safety check).
  IGNORE("dkim._domainkey", "TXT"),

  // Web
  A("@", VPS_V4),
  A("*", VPS_V4),
  AAAA("@", VPS_V6),
  AAAA("*", VPS_V6),
  CAA("@", "issue", "letsencrypt.org"),
  CNAME("status", "reports.hetrixtools.com."),

  // Mail (Mailcow)
  A("mail", VPS_V4),
  A("*.mail", VPS_V4),
  MX("@", 5, MAIL),
  CNAME("autoconfig", MAIL),
  CNAME("autodiscovery", MAIL),
  TXT("@", "v=spf1 mx a -all"),
  TXT("_dmarc", "v=DMARC1; p=reject; rua=mailto:dmarc-reports@mljr.eu"),
  TXT("default._bimi", "v=BIMI1; l=https://mljr.eu/logo/logo.svg; a="),
  SRV("_autodiscover._tcp", 0, 1, 443, MAIL),
  SRV("_caldavs._tcp", 0, 1, 443, MAIL),
  TXT("_caldavs._tcp", "path=/SOGo/dav/"),
  SRV("_carddavs._tcp", 0, 1, 443, MAIL),
  TXT("_carddavs._tcp", "path=/SOGo/dav/"),
  SRV("_imap._tcp", 0, 1, 143, MAIL),
  SRV("_imaps._tcp", 0, 1, 993, MAIL),
  SRV("_pop3._tcp", 0, 1, 110, MAIL),
  SRV("_pop3s._tcp", 0, 1, 995, MAIL),
  SRV("_sieve._tcp", 0, 1, 4190, MAIL),
  SRV("_smtps._tcp", 0, 1, 465, MAIL),
  SRV("_submission._tcp", 0, 1, 587, MAIL),
  SRV("_submissions._tcp", 0, 1, 465, MAIL),

  // Site verification
  TXT("@", "google-site-verification=vHuU3zYh15HV8UQkLzi_KicmWgGshuIXL8CBzvzzwd4"),

  // Present in the live zone; purpose unclear (DS record for "ds.mljr.eu").
  DS("ds", 28826, 13, 2, "5b1db5474adc74eea5f8e32a6d28e15cd6c920995ceba33fc2797ac2863fd437")
);
