all:
  children:
    rocky:
      hosts:
        mljr:
          ansible_host: mljr.tail33930.ts.net
          ansible_user: root
        homeserver:
          ansible_host: nuc.tail33930.ts.net
          ansible_user: root
    debian:
      hosts:
        pi:
          ansible_host: pi.tail33930.ts.net
          ansible_user: pi
    unraid:
      hosts:
        nas:
          ansible_host: nas.tail33930.ts.net
          ansible_user: root
    docker_hosts:
      children:
        rocky:
        debian:
