// Package collectors holds every healthreport data source. Importing a
// collector's package registers it into healthreport.Registry, mirroring
// the Python original's decorator-based registration via import side
// effects.
package collectors

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"
)

// httpGet performs a GET and returns an error unless the response is 2xx,
// mirroring requests.Response.raise_for_status().
func httpGet(targetURL string, timeout time.Duration, modify func(*http.Request)) (*http.Response, error) {
	client := &http.Client{Timeout: timeout}
	req, err := http.NewRequest(http.MethodGet, targetURL, nil)
	if err != nil {
		return nil, err
	}
	if modify != nil {
		modify(req)
	}
	resp, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		body, _ := io.ReadAll(io.LimitReader(resp.Body, 500))
		resp.Body.Close()
		return nil, fmt.Errorf("%s: HTTP %d: %s", targetURL, resp.StatusCode, string(body))
	}
	return resp, nil
}

// grafanaExploreURL builds a deep link into Grafana Explore for a LogQL
// query against the Loki datasource, so a log-derived finding in the email
// is one click instead of "go copy this query into Grafana yourself". "loki"
// is a pinned, not autogenerated, datasource uid (services/grafana/
// provisioning/datasources/datasources.yml), safe to hardcode here.
func grafanaExploreURL(grafanaBaseURL, logql string) string {
	if grafanaBaseURL == "" || logql == "" {
		return ""
	}
	pane := map[string]any{
		"datasource": "loki",
		"queries": []map[string]any{{
			"refId":      "A",
			"expr":       logql,
			"datasource": map[string]string{"type": "loki", "uid": "loki"},
		}},
		"range": map[string]string{"from": "now-24h", "to": "now"},
	}
	panesJSON, err := json.Marshal(map[string]any{"p1": pane})
	if err != nil {
		return ""
	}
	q := url.Values{}
	q.Set("schemaVersion", "1")
	q.Set("panes", string(panesJSON))
	q.Set("orgId", "1")
	return strings.TrimRight(grafanaBaseURL, "/") + "/explore?" + q.Encode()
}
