#!/bin/bash
set -euo pipefail

: "${POSTGRES_DB:?POSTGRES_DB must be set}"
: "${POSTGRES_USER:?POSTGRES_USER must be set}"
: "${NOCTURNE_MIGRATOR_PASSWORD:?NOCTURNE_MIGRATOR_PASSWORD must be set}"
: "${NOCTURNE_APP_PASSWORD:?NOCTURNE_APP_PASSWORD must be set}"
: "${NOCTURNE_WEB_PASSWORD:?NOCTURNE_WEB_PASSWORD must be set}"

psql \
    --username "$POSTGRES_USER" \
    --dbname "$POSTGRES_DB" \
    --set ON_ERROR_STOP=on \
    --set DBNAME="$POSTGRES_DB" \
    --set migrator_password="$NOCTURNE_MIGRATOR_PASSWORD" \
    --set app_password="$NOCTURNE_APP_PASSWORD" \
    --set web_password="$NOCTURNE_WEB_PASSWORD" \
    <<'SQL'
CREATE ROLE nocturne_migrator LOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE PASSWORD :'migrator_password';
CREATE ROLE nocturne_app      LOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE PASSWORD :'app_password';
CREATE ROLE nocturne_web      LOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE PASSWORD :'web_password';

ALTER DATABASE :"DBNAME" OWNER TO nocturne_migrator;
ALTER SCHEMA public OWNER TO nocturne_migrator;

GRANT CONNECT ON DATABASE :"DBNAME" TO nocturne_app;
GRANT USAGE ON SCHEMA public TO nocturne_app;

GRANT CONNECT ON DATABASE :"DBNAME" TO nocturne_web;
GRANT USAGE, CREATE ON SCHEMA public TO nocturne_web;

ALTER DEFAULT PRIVILEGES FOR ROLE nocturne_migrator IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO nocturne_app;
ALTER DEFAULT PRIVILEGES FOR ROLE nocturne_migrator IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO nocturne_app;
SQL
