services:
  speedtest:
    image: openspeedtest/latest:latest
    container_name: ${COMPOSE_PROJECT_NAME:-speedtest-staging}
    restart: unless-stopped
    ports:
      - "18090:3000"
    networks:
      - speedtest

networks:
  speedtest:
    driver: bridge
