forge 'https://forgeapi.puppet.com'

# Keep the complete dependency closure explicit. `puppet module install` would
# otherwise resolve transitive dependencies to whatever is newest that day.
# Renovate understands this format and opens update PRs for Forge releases.
mod 'puppetlabs/stdlib',      '9.7.0'
mod 'puppetlabs/augeas_core', '1.5.0'
mod 'puppetlabs/apt',         '11.3.2'
mod 'puppetlabs/pwshlib',     '2.0.1'
mod 'puppetlabs/powershell',  '6.1.0'
mod 'puppetlabs/reboot',      '5.1.0'
mod 'puppet/firewalld',       '5.1.0'
mod 'puppetlabs/docker',      '10.4.1'
