---
homepage_data_sync_path: /opt/homepage/data
homepage_data_sync_url: https://raw.githubusercontent.com/MrCodeEU/mljr-data/master/generated/site-data.json
homepage_data_sync_schedule: "*:0/15"  # every 15 minutes
