services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    environment:
      - TZ=Europe/Vienna
    volumes:
      - ./config:/config
    network_mode: host
    restart: unless-stopped
    privileged: true
