services:
  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy
    restart: unless-stopped
    ports:
      - "${BIND_ADDR:-127.0.0.1}:2586:80"
    volumes:
      - ntfy-cache:/var/cache/ntfy
      - ntfy-data:/var/lib/ntfy
      - ./server.yml:/etc/ntfy/server.yml:ro
    environment:
      - TZ=${TZ}
    command: serve

volumes:
  ntfy-cache:
  ntfy-data:


