#!/bin/bash
# Configuration generator script
# Reads services.yml and generates Caddyfile, Glance config, and docker-compose configurations

set -e

echo "========================================="
echo "Generating Configurations from YAML"
echo "========================================="

CONFIG_FILE="${1:-/tmp/homelab-deploy/configs/services.yml}"
CADDY_OUTPUT_DIR="${2:-/opt/caddy}"
GLANCE_OUTPUT_DIR="${3:-/opt/glance}"
INVENTORY_FILE="${4:-/tmp/homelab-deploy/inventory.yml}"

echo "Config file: $CONFIG_FILE"
echo "Caddy output: $CADDY_OUTPUT_DIR"
echo "Glance output: $GLANCE_OUTPUT_DIR"
echo "Inventory file: $INVENTORY_FILE"
echo ""

if [ ! -f "$CONFIG_FILE" ]; then
    echo "❌ Error: Configuration file not found: $CONFIG_FILE"
    echo "Looking for file..."
    ls -la "$(dirname "$CONFIG_FILE")" || echo "Directory doesn't exist"
    exit 1
fi

echo "✓ Configuration file found"

# Check if yq is available
if ! command -v yq &> /dev/null; then
    echo "Installing yq for YAML parsing..."
    wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
    chmod +x /usr/local/bin/yq
fi

echo "Reading configuration from: $CONFIG_FILE"
mkdir -p "$CADDY_OUTPUT_DIR"
mkdir -p "$GLANCE_OUTPUT_DIR"

# Extract global configuration
DOMAIN=$(yq eval '.global.domain // "example.com"' "$CONFIG_FILE")
EMAIL=$(yq eval '.global.email // "admin@example.com"' "$CONFIG_FILE")
LOCATION=$(yq eval '.global.location // "London, United Kingdom"' "$CONFIG_FILE")
DASHBOARD_NAME=$(yq eval '.dashboard.name // "Homelab Dashboard"' "$CONFIG_FILE")
TIMEZONE=$(yq eval '.dashboard.timezone // "Europe/London"' "$CONFIG_FILE")

# Generate Caddyfile
echo "Generating Caddyfile..."
CADDYFILE="$CADDY_OUTPUT_DIR/Caddyfile"

# Start Caddyfile
cat > "$CADDYFILE" << EOF
# Auto-generated Caddyfile
# Generated from services.yml
# Email for Let's Encrypt: $EMAIL

{
    email $EMAIL
}

# Default route for base domain
$DOMAIN {
    root * /srv
    file_server
}

EOF

# Generate default index.html
mkdir -p "$CADDY_OUTPUT_DIR/site"
cat > "$CADDY_OUTPUT_DIR/site/index.html" << EOF
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Homelab Automation</title>
    <style>
        body { font-family: system-ui, -apple-system, sans-serif; background: #1a1a1a; color: #e0e0e0; display: flex; justify-content: center; align-items: center; height: 100vh; margin: 0; }
        .container { text-align: center; padding: 2rem; border: 1px solid #333; border-radius: 8px; background: #252525; }
        h1 { color: #4caf50; margin-bottom: 0.5rem; }
        p { color: #aaa; }
        .meta { font-size: 0.8rem; margin-top: 1.5rem; color: #666; }
    </style>
</head>
<body>
    <div class="container">
        <h1>Deployment Successful</h1>
        <p>Caddy is running and serving traffic.</p>
        <div class="meta">
            Last Updated: $(date)<br>
            Generated by Homelab Automation
        </div>
    </div>
</body>
</html>
EOF

# Parse services and generate Caddy blocks
SERVICE_COUNT=$(yq eval '.services | length' "$CONFIG_FILE")

if [ "$SERVICE_COUNT" -gt 0 ]; then
    for i in $(seq 0 $((SERVICE_COUNT - 1))); do
        SERVICE_NAME=$(yq eval ".services[$i].name" "$CONFIG_FILE")
        DOMAIN=$(yq eval ".services[$i].domain // \"\"" "$CONFIG_FILE")
        PORT=$(yq eval ".services[$i].port // \"\"" "$CONFIG_FILE")
        HOST=$(yq eval ".services[$i].host // \"\"" "$CONFIG_FILE")
        UPSTREAM=$(yq eval ".services[$i].upstream // \"\"" "$CONFIG_FILE")
        ENABLED=$(yq eval ".services[$i].enabled // true" "$CONFIG_FILE")
        SKIP_DEPLOY=$(yq eval ".services[$i].skip_deploy // false" "$CONFIG_FILE")
        
        # Skip if not enabled, explicitly skipped, or no domain
        if [ "$ENABLED" != "true" ] || [ "$SKIP_DEPLOY" = "true" ] || [ -z "$DOMAIN" ]; then
            continue
        fi
        
        # Determine the upstream target
        if [ -n "$UPSTREAM" ]; then
            # Use custom upstream URL
            TARGET="$UPSTREAM"
        elif [ -n "$PORT" ]; then
          # Build target from host:port
          EFFECTIVE_HOST="$HOST"
          
          # Check if host is defined in inventory
          IS_IN_INVENTORY="false"
          if [ -n "$EFFECTIVE_HOST" ] && [ "$EFFECTIVE_HOST" != "localhost" ] && [ "$EFFECTIVE_HOST" != "null" ] && [ -f "$INVENTORY_FILE" ]; then
             IS_IN_INVENTORY=$(yq eval ".devices | has(\"$EFFECTIVE_HOST\")" "$INVENTORY_FILE")
          fi

          if [ "$IS_IN_INVENTORY" = "true" ]; then
             # Get primary hostname
             PRIMARY_HOST=$(yq eval ".devices.$EFFECTIVE_HOST.hostname" "$INVENTORY_FILE")
             TARGET="$PRIMARY_HOST:$PORT"
             
             # Get fallbacks
             FALLBACK_COUNT=$(yq eval ".devices.$EFFECTIVE_HOST.fallbacks | length" "$INVENTORY_FILE")
             if [ "$FALLBACK_COUNT" -gt 0 ] && [ "$FALLBACK_COUNT" != "null" ]; then
                 for j in $(seq 0 $((FALLBACK_COUNT - 1))); do
                     FB_HOST=$(yq eval ".devices.$EFFECTIVE_HOST.fallbacks[$j]" "$INVENTORY_FILE")
                     TARGET="$TARGET $FB_HOST:$PORT"
                 done
             fi
             echo "  - Resolved $EFFECTIVE_HOST to $TARGET"
          elif [ -z "$EFFECTIVE_HOST" ] || [ "$EFFECTIVE_HOST" = "localhost" ] || [ "$EFFECTIVE_HOST" = "null" ]; then
            # Default to service name so Caddy can reach the container via the shared Docker network
            EFFECTIVE_HOST="$SERVICE_NAME"
            TARGET="$EFFECTIVE_HOST:$PORT"
          else
            TARGET="$EFFECTIVE_HOST:$PORT"
          fi
        else
            echo "⚠️  Skipping $SERVICE_NAME: No port or upstream defined"
            continue
        fi
        
        # Add to Caddyfile
        echo "" >> "$CADDYFILE"
        echo "# $SERVICE_NAME" >> "$CADDYFILE"
        echo "$DOMAIN {" >> "$CADDYFILE"
        echo "    reverse_proxy $TARGET" >> "$CADDYFILE"
        echo "}" >> "$CADDYFILE"
        
        # Log what was added
        if [ -n "$UPSTREAM" ]; then
            echo "✓ Caddy: Added $SERVICE_NAME: $DOMAIN -> $UPSTREAM"
        else
            echo "✓ Caddy: Added $SERVICE_NAME: $DOMAIN -> $TARGET"
        fi
    done
else
    echo "No services found in configuration"
fi

echo "Caddyfile generated at: $CADDYFILE"

# Format Caddyfile if docker is available (matches Caddy's fmt warning)
if command -v docker &> /dev/null; then
  echo "Formatting Caddyfile with caddy fmt..."
  docker run --rm -v "$CADDY_OUTPUT_DIR:/etc/caddy" caddy:latest caddy fmt --overwrite /etc/caddy/Caddyfile || echo "⚠️  caddy fmt failed; continuing"
else
  echo "⚠️  Docker not available; skipping caddy fmt"
fi

# Generate Glance configuration
echo ""
echo "Generating Glance configuration..."
GLANCE_CONFIG="$GLANCE_OUTPUT_DIR/glance.yml"

# Check if template exists
TEMPLATE_PATH="/tmp/homelab-deploy/configs/glance/glance.yml.template"
if [ -f "$TEMPLATE_PATH" ]; then
    # Use template and replace variables
    cat "$TEMPLATE_PATH" | \
        sed "s/\${LOCATION}/$LOCATION/g" | \
        sed "s/\${SERVER_NAME}/$(hostname)/g" | \
        sed "s/\${DASHBOARD_NAME}/$DASHBOARD_NAME/g" > "$GLANCE_CONFIG"
    
    echo "✓ Glance config generated from template at: $GLANCE_CONFIG"
else
    # Create minimal Glance config
    cat > "$GLANCE_CONFIG" << EOF
# Glance Dashboard Configuration
# Auto-generated from services.yml

server:
  port: 8080

theme:
  background-color: 240 8 9
  primary-color: 43 50 70

pages:
  - name: Home
    columns:
      - size: small
        widgets:
          - type: weather
            location: $LOCATION
            
      - size: full
        widgets:
          - type: docker-containers
            title: Services
            
      - size: small
        widgets:
          - type: monitor
            title: Health
            sites:
EOF

    # Add monitored services
    for i in $(seq 0 $((SERVICE_COUNT - 1))); do
        SERVICE_NAME=$(yq eval ".services[$i].name" "$CONFIG_FILE")
        SERVICE_DOMAIN=$(yq eval ".services[$i].domain // \"\"" "$CONFIG_FILE")
        ENABLED=$(yq eval ".services[$i].enabled // true" "$CONFIG_FILE")
        SKIP_DEPLOY=$(yq eval ".services[$i].skip_deploy // false" "$CONFIG_FILE")
        ICON=$(yq eval ".services[$i].icon // \"\"" "$CONFIG_FILE")
        
        if [ "$ENABLED" = "true" ] && [ "$SKIP_DEPLOY" != "true" ] && [ -n "$SERVICE_DOMAIN" ]; then
            cat >> "$GLANCE_CONFIG" << EOF
              - title: $SERVICE_NAME
                url: https://$SERVICE_DOMAIN
EOF
            if [ -n "$ICON" ]; then
                echo "                icon: $ICON" >> "$GLANCE_CONFIG"
            fi
        fi
    done
    
    echo "✓ Glance: Created minimal config at: $GLANCE_CONFIG"
fi

# Generate docker-compose for Glance
echo ""
echo "Generating Glance docker-compose..."
cat > "$GLANCE_OUTPUT_DIR/docker-compose.yml" << 'EOF'
version: '3.8'

services:
  glance:
    image: glanceapp/glance:latest
    container_name: glance
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./glance.yml:/app/config/glance.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=${TIMEZONE}
    networks:
      - caddy_network

networks:
  caddy_network:
    external: true
EOF

echo "✓ Glance docker-compose generated"

echo ""
echo "========================================="
echo "Configuration Generation Complete!"
echo "========================================="
echo ""
echo "Generated files:"
echo "  • Caddyfile: $CADDYFILE"
echo "  • Glance config: $GLANCE_CONFIG"
echo "  • Glance compose: $GLANCE_OUTPUT_DIR/docker-compose.yml"
