#!/bin/bash
# Fail2ban setup script for Rocky Linux
# Monitors SSH and Caddy logs and bans malicious IPs

set -e

# Source common functions
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [ -f "$SCRIPT_DIR/common.sh" ]; then
    source "$SCRIPT_DIR/common.sh"
else
    log_info() { echo "[INFO] $1"; }
    log_success() { echo "[SUCCESS] $1"; }
    log_error() { echo "[ERROR] $1"; }
    log_header() { echo "=== $1 ==="; }
    set_error_trap() { set -e; }
fi

set_error_trap

log_header "Starting Fail2ban Setup"

FAIL2BAN_DIR="/etc/fail2ban"
NTFY_URL="${1:-https://ntfy.mljr.eu}"

# Install fail2ban if not present
if ! command -v fail2ban-client &> /dev/null; then
    log_info "Installing fail2ban..."
    dnf install -y fail2ban fail2ban-systemd
    systemctl enable fail2ban
    log_success "Fail2ban installed"
else
    log_success "Fail2ban is already installed"
fi

# Create custom configuration directory
mkdir -p "$FAIL2BAN_DIR/filter.d"
mkdir -p "$FAIL2BAN_DIR/action.d"
mkdir -p "$FAIL2BAN_DIR/jail.d"

# Create filter for Caddy basic auth failures
log_info "Creating Caddy basic auth filter..."
cat > "$FAIL2BAN_DIR/filter.d/caddy-basicauth.conf" << 'EOF'
# Fail2ban filter for Caddy basic auth failures
# Matches JSON log entries with 401 status (unauthorized)

[Definition]
failregex = ^.*"status":401.*"remote_ip":"<HOST>".*$
ignoreregex =

# Example log line:
# {"level":"info","ts":1234567890.123,"logger":"http.log.access","msg":"handled request","request":{"remote_ip":"1.2.3.4","remote_port":"12345","client_ip":"1.2.3.4","proto":"HTTP/2.0","method":"GET","host":"logs.mljr.eu","uri":"/","headers":{"User-Agent":["curl/7.68.0"]}},"status":401}
EOF

# Create filter for Caddy general bad requests (optional, commented out by default)
log_info "Creating Caddy bad request filter..."
cat > "$FAIL2BAN_DIR/filter.d/caddy-badbots.conf" << 'EOF'
# Fail2ban filter for Caddy bad bots and exploit attempts
# This filter is disabled by default - enable in jail.local if needed

[Definition]
# Match common exploit attempts in URI
failregex = ^.*"status":(403|444).*"remote_ip":"<HOST>".*"uri":".*(/wp-admin|/phpmyadmin|/.env|/.git|/admin).*".*$
            ^.*"remote_ip":"<HOST>".*"uri":".*(\.\.|/etc/passwd|/proc/self|SELECT.*FROM|UNION.*SELECT).*".*$

ignoreregex =
EOF

# Create ntfy notification action
log_info "Creating ntfy notification action..."
cat > "$FAIL2BAN_DIR/action.d/ntfy.conf" << EOF
# Fail2ban action to send notifications via ntfy
#
# To enable, add to your jail:
#   action = iptables-multiport[name=<name>, port="<port>", protocol=<protocol>]
#            ntfy[ntfy_url="$NTFY_URL"]

[Definition]

# Option: ntfy_url
# Notes.: URL of your ntfy server
# Values: URL
ntfy_url = $NTFY_URL

# Option: ntfy_topic
# Notes.: ntfy topic to send to
# Values: STRING
ntfy_topic = fail2ban

# Option: ntfy_priority
# Notes.: Priority level (1=min, 3=default, 5=max)
# Values: INT
ntfy_priority = 4

# Ban action - send notification when IP is banned
actionban = curl -X POST -H "Title: 🚫 Fail2ban: IP Banned" \\
                -H "Priority: <ntfy_priority>" \\
                -H "Tags: warning,security" \\
                -d "Jail: <name>
IP: <ip>
Failures: <failures>
Time: \$(date '+%%Y-%%m-%%d %%H:%%M:%%S')

The IP address <ip> has been banned after <failures> failed attempts." \\
                <ntfy_url>/<ntfy_topic>

# Unban action - send notification when IP is unbanned (optional, commented out to reduce noise)
#actionunban = curl -X POST -H "Title: ✅ Fail2ban: IP Unbanned" \\
#                -H "Priority: 2" \\
#                -H "Tags: info,security" \\
#                -d "Jail: <name>
#IP: <ip>
#Time: \$(date '+%%Y-%%m-%%d %%H:%%M:%%S')
#
#The IP address <ip> has been unbanned." \\
#                <ntfy_url>/<ntfy_topic>

[Init]
name = default
ntfy_priority = 4
EOF

# Create jail configuration
log_info "Creating jail configuration..."
cat > "$FAIL2BAN_DIR/jail.d/homelab.conf" << EOF
# Homelab fail2ban jail configuration
# Generated by homelab automation

[DEFAULT]
# Ban settings
bantime  = 86400      # 24 hours
findtime = 600        # 10 minutes
maxretry = 5          # 5 failures

# Notification action - add ntfy to all jails
action = %(action_mwl)s
         ntfy[ntfy_url="$NTFY_URL", ntfy_topic="fail2ban"]

# Ignore local/private IPs
ignoreip = 127.0.0.1/8 ::1
           10.0.0.0/8
           172.16.0.0/12
           192.168.0.0/16
           100.64.0.0/10

# SSH jail - protect SSH access
[sshd]
enabled  = true
port     = ssh
filter   = sshd
logpath  = /var/log/secure
maxretry = 5
bantime  = 86400

# Caddy basic auth jail - protect basic auth endpoints
[caddy-basicauth]
enabled  = true
port     = http,https
filter   = caddy-basicauth
logpath  = /opt/caddy/logs/access.log
maxretry = 5
bantime  = 86400

# Caddy bad bots jail - DISABLED by default
# Uncomment to enable protection against exploit attempts
#[caddy-badbots]
#enabled  = true
#port     = http,https
#filter   = caddy-badbots
#logpath  = /opt/caddy/logs/access.log
#maxretry = 3
#bantime  = 86400
EOF

# Ensure Caddy logs directory exists and is readable
log_info "Ensuring Caddy logs are accessible..."
mkdir -p /opt/caddy/logs
touch /opt/caddy/logs/access.log
chmod 644 /opt/caddy/logs/access.log

# Start and enable fail2ban
log_info "Starting fail2ban service..."
systemctl restart fail2ban
systemctl enable fail2ban

# Wait a moment for fail2ban to start
sleep 2

# Show status
log_success "Fail2ban setup complete!"
echo ""
log_info "Checking fail2ban status..."
fail2ban-client status

echo ""
log_info "Active jails:"
fail2ban-client status | grep "Jail list" | sed 's/.*://;s/,//g'

echo ""
log_success "Fail2ban is now protecting your homelab!"
echo ""
echo "Configuration details:"
echo "  - Ban time: 24 hours"
echo "  - Max retries: 5 attempts"
echo "  - Find time: 10 minutes"
echo "  - Notifications: $NTFY_URL/fail2ban"
echo ""
echo "To check jail status:"
echo "  fail2ban-client status"
echo "  fail2ban-client status sshd"
echo "  fail2ban-client status caddy-basicauth"
echo ""
echo "To unban an IP:"
echo "  fail2ban-client set sshd unbanip <IP>"
echo ""
