#!/usr/bin/env bash
# One-shot migration: ansible-vault (ansible/inventory/group_vars/all/vault.yml)
# -> openvox/data/common.eyaml (hiera-eyaml, consumed via Hiera lookups in
# Puppet manifests). Mirrors scripts/vault-to-spot-secrets.sh's approach for
# the earlier spot migration.
#
# Safe by construction: the vault is decrypted only in memory (via
# `ansible-vault view`, piped straight into a Python parser - never written
# to disk unencrypted). Each value is encrypted with the eyaml PKCS7 public
# key (openvox/keys/public_key.pkcs7.pem) via subprocess with real argv
# (never shell-interpolated), so values containing quotes/backslashes/
# newlines can't break the encryption call. The private key
# (openvox/keys/private_key.pkcs7.pem) is never read by this script at all -
# encryption only needs the public key.
#
# Re-running is safe: this always regenerates the full output file, so it's
# idempotent per key (the ciphertext output itself will differ run to run
# since PKCS7 encryption is non-deterministic, but that's expected and
# harmless - only the decrypted value's identity matters).
#
# Usage: ./scripts/vault-to-openvox-secrets.sh [--out PATH] [--dry-run]
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VAULT_FILE="$REPO_ROOT/ansible/inventory/group_vars/all/vault.yml"
PUBLIC_KEY="$REPO_ROOT/openvox/keys/public_key.pkcs7.pem"
OUT_FILE="$REPO_ROOT/openvox/data/common.eyaml"
DRY_RUN=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        --out) OUT_FILE="$2"; shift 2 ;;
        --dry-run) DRY_RUN=1; shift ;;
        *) echo "unknown arg: $1" >&2; exit 1 ;;
    esac
done

EYAML_BIN="$(command -v eyaml || true)"
if [[ -z "$EYAML_BIN" ]]; then
    EYAML_BIN="$HOME/.local/share/gem/ruby/4.0.0/bin/eyaml"
fi
if [[ ! -x "$EYAML_BIN" ]]; then
    echo "eyaml not found - run: gem install --user-install hiera-eyaml" >&2
    exit 1
fi

if [[ ! -f "$PUBLIC_KEY" ]]; then
    echo "ERROR: $PUBLIC_KEY not found - generate the keypair first:" >&2
    echo "  eyaml createkeys --pkcs7-public-key=openvox/keys/public_key.pkcs7.pem --pkcs7-private-key=openvox/keys/private_key.pkcs7.pem" >&2
    exit 1
fi

if [[ ! -f "$VAULT_FILE" ]]; then
    echo "ERROR: $VAULT_FILE not found." >&2
    exit 1
fi

echo "This reads every key out of:"
echo "  $VAULT_FILE"
echo "and writes it, individually PKCS7-encrypted, into:"
echo "  $OUT_FILE"
echo "It does NOT touch or delete vault.yml - that stays the source of"
echo "truth until every role that consumes a given key has been ported."
echo "Only the PUBLIC key is used - the private key is never read by this script."
echo

read -rsp "Ansible Vault password: " VAULT_PASS
echo
VAULT_PASS_FILE=$(mktemp)
chmod 600 "$VAULT_PASS_FILE"
printf '%s' "$VAULT_PASS" > "$VAULT_PASS_FILE"
unset VAULT_PASS

cleanup() { rm -f "$VAULT_PASS_FILE"; }
trap cleanup EXIT INT TERM

mkdir -p "$(dirname "$OUT_FILE")"

# Decrypt straight into a Python process that itself calls eyaml via
# subprocess (real argv, not shell interpolation) for every key.
ansible-vault view "$VAULT_FILE" --vault-password-file "$VAULT_PASS_FILE" \
    | EYAML_BIN="$EYAML_BIN" PUBLIC_KEY="$PUBLIC_KEY" OUT_FILE="$OUT_FILE" DRY_RUN="$DRY_RUN" python3 -c '
import os, subprocess, sys, yaml

data = yaml.safe_load(sys.stdin) or {}
eyaml_bin = os.environ["EYAML_BIN"]
public_key = os.environ["PUBLIC_KEY"]
out_file = os.environ["OUT_FILE"]
dry_run = os.environ["DRY_RUN"] == "1"

lines = ["# Generated by scripts/vault-to-openvox-secrets.sh - do not hand-edit.",
         "# Encrypted with openvox/keys/public_key.pkcs7.pem, decryptable only",
         "# with openvox/keys/private_key.pkcs7.pem (never committed - see",
         "# .gitignore). Re-run the script to add/update keys."]

total = 0
set_count = 0
for key, value in data.items():
    if value is None or value == "":
        continue
    total += 1
    if dry_run:
        print(f"would encrypt: {key}")
        set_count += 1
        continue
    result = subprocess.run(
        [eyaml_bin, "encrypt", "-s", str(value),
         "--pkcs7-public-key", public_key,
         "--pkcs7-private-key", "/dev/null",
         "-o", "string"],
        check=True, capture_output=True, text=True,
    )
    enc = result.stdout.strip()
    lines.append(f"\"{key}\": \"{enc}\"")
    print(f"encrypted: {key}")
    set_count += 1

print()
if dry_run:
    print(f"Dry run: would encrypt {set_count} of {total} non-empty vault keys.")
else:
    with open(out_file, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Encrypted {set_count} of {total} non-empty vault keys into {out_file}.")
    print(f"Verify with: eyaml decrypt -f {out_file} --pkcs7-private-key openvox/keys/private_key.pkcs7.pem --pkcs7-public-key {public_key}")
'
