services:
  beszel-hub:
    image: henrygd/beszel:latest
    container_name: ${COMPOSE_PROJECT_NAME:-beszel}
    restart: unless-stopped
    ports:
      - "${PORT:-8090}:8090"
    volumes:
      - beszel-data:/beszel_data
    environment:
      TZ: ${TZ:-Europe/Vienna}
    networks:
      - default
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  beszel-data:

networks:
  default:
    driver: bridge
